accounts/urls.py
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import custom_login, custom_logout, custom_register

app_name = 'accounts'

urlpatterns = [
    path('login/', custom_login, name='login'),
    path('logout/', custom_logout, name='logout'),
    path('register/', custom_register, name='register'),
    path('password_reset/',
         auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done'), template_name='registration/password_reset_form.html'),
         name="password_reset"),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('accounts:password_reset_complete')), name="password_reset_confirm"),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

marjikon/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('users/', include(('accounts.urls', 'accounts'), namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += [
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.utils.translation import gettext_lazy as _


# Create your models here.

class CustomUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Email adresi gereklidir')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser için is_staff=True olmalıdır.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser için is_superuser=True olmalıdır.')

        return self._create_user(email, password, **extra_fields)
    


class CustomUser(AbstractBaseUser,PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now)
    is_seller = models.BooleanField(default=False)

    object = CustomUserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email
    
    def get_full_name(self):
        return self.email
    
    def get_short_name(self):
        return self.email


class PersonalInfo(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=150)
    birth_date = models.DateField(_('birth date'), null=True, blank=True)
    GENDER_CHOICES = [
        ('M', _('Male')),
        ('F', _('Female')),
        ('O', _('Other')),
    ]
    gender = models.CharField(_('gender'), max_length=1, choices=GENDER_CHOICES)

    def __str__(self):
        if self.first_name == "":
            return self.user.email
        else: 
            return f"{self.first_name} {self.last_name}"


class CustomAddress(models.Model):
    user = models.ForeignKey('CustomUser', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=150)
    phone_number = models.CharField(_('phone number'), max_length=11)
    city = models.CharField(_('city'), max_length=100)
    district = models.CharField(_('state'), max_length=200)
    neighborhood = models.CharField(_('neighborhood'), max_length=100)
    address = models.TextField()
    address_title = models.CharField(max_length=100)

    BILING_TYPE_CHOICES = (
        ('personal', 'Bireysel'),
        ('corporate', 'Kurumsal')
    )
    billing_type = models.CharField(_('biling type'), blank=True, choices=BILING_TYPE_CHOICES, max_length=100)
    tax_number = models.CharField(_('tax number'), max_length=20, blank=True)
    tax_office = models.CharField(_('tax office'), max_length=100, blank=True)
    company_name = models.CharField(_('company name'), max_length=100, blank=True)

    def __str__(self):
        return f"{self.address_title} - {self.user.email}"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.address_title)
        original_slug = self.slug
        counter = 1
        while CustomAddress.objects.filter(slug=self.slug).exclude(id=self.id).exists():
            self.slug = f'{original_slug}-{counter}'
            counter += 1
        super().save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('email',)
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from .forms import CustomUserCreationForm
from django.contrib import messages
from django.utils.translation import gettext_lazy as _
# Create your views here.

def custom_login(request):
    if request.user.is_authenticated:
        return redirect('index')
    
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)

        if user is not None:
            if user.is_seller:
                messages.error(request, _('Böyle Bir Kullanıcı Bulunamadı'))
                return redirect('users:login')
            else:
                login(request, user)
                return redirect('index')
        else:
            messages.error(request, _('Yanlış kullanıcı adı veya şifre'))

    return render(request, 'registration/login.html')

def custom_register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})


def custom_logout(request):
    logout(request)
    messages.success(request, _('Başarıyla Çıkış Yaptınız'))
    return redirect('users:login')

marjikon/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'shop/index.html')

templates/accounts/password_reset_form.html
{% extends 'base/base.html' %}


{% block wrapper %}

<div class="container">
    {% block content %}
  <h2>Şifre Sıfırlama</h2>
  <form method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Şifre Sıfırlama Linki Gönder</button>
  </form>
{% endblock %}

</div>
    
{% endblock  %}
    

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <!-- ========== STYLESHEETS ========== -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
          integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>

</head>

<body>
<div class="wrapper">
    <!-- Top Bar -->
    <div class="top-bar">
        <p>Yeni Üyelere Özel Sepette %10 İndirim <span>KOD:OZEL10UYE</span></p>
    </div>
    <!-- Header -->
    <header>
        <div class="main-header">
            <div class="container">
                <!-- Navigation -->
                <nav class="header-menu">
                    <ul class="navbar">
                        <li class="menu-item">
                            <a href="" class="menu-link">
                                Kadın
                            </a>
                            <div class="mega-menu">
                                <div class="container">
                                    <ul>
                                        <li><a href="">Test 01 Menu</a></li>
                                        <li><a href="">Test 02 Menu</a></li>
                                        <li><a href="">Test 03 Menu</a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                        <li class="menu-item">
                            <a href="" class="menu-link">Erkek</a>
                        </li>
                        <li class="menu-item">
                            <a href="" class="menu-link">Çocuk</a>
                        </li>
                        <li class="menu-item">
                            <a href="" class="menu-link">Elektronik</a>
                        </li>
                        <li class="menu-item">
                            <a href="" class="menu-link">Ofis</a>
                        </li>
                        <li class="menu-item">
                            <a href="" class="menu-link">Yaşam</a>
                        </li>
                    </ul>
                </nav>
                <div class="header-logo">
                    <a href="{% url 'index' %}">
                        <img src="{% static 'images/marjikon.png' %}" alt="" class="m-logo">
                    </a>
                </div>
                <div class="header-auth">
                    {% if user.is_authenticated %}
                        <div class="mr-5">
                            <ul class="flex">
                                <li class="flex ">
                                    <a href="#" class="flex">
                                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" class="w-5 h-5 mr-2">
                                        <path d="M304 128a80 80 0 1 0 -160 0 80 80 0 1 0 160 0zM96 128a128 128 0 1 1 256 0A128 128 0 1 1 96 128zM49.3 464H398.7c-8.9-63.3-63.3-112-129-112H178.3c-65.7 0-120.1 48.7-129 112zM0 482.3C0 383.8 79.8 304 178.3 304h91.4C368.2 304 448 383.8 448 482.3c0 16.4-13.3 29.7-29.7 29.7H29.7C13.3 512 0 498.7 0 482.3z"/>
                                    </svg>
                                    Hesabım</a>
                                    <ul>
                                        <li class="hidden hover:block">
                                            <a href="">Siparişlerim</a>
                                            <a href="">Değerlendirmelerim</a>
                                            <a href="">Kullanıcı Bilgilerim</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <a href="{% url 'accounts:logout' %}">Çıkış Yap</a>
                        </div>
                    {% else %}
                        <a href="{% url 'accounts:login' %}" class="btn btn-black">Giriş Yap</a>
                        <a href="{% url 'accounts:register' %}" class="btn btn-black">Kayıt Ol</a>
                    {% endif %}
                </div>
            </div>
        </div>

    </header>
    <main class="main">
        {% block wrapper %}

        {% endblock %}
    </main>

    <!-- Footer -->
    <footer class="footer">
        <div class="container">
            <div class="footer-about">
                <h2 class="footer-title">Marjikon</h2>
                <ul class="footer-about__navbar">
                    <li class="footer-item">
                        <a href="">Biz Kimiz</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">İletişim</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Satıcı Ol</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Kariyer</a>
                    </li>

                </ul>
            </div>
            <div class="footer-auth">
                <h2 class="footer-title">Üye İşlemleri</h2>
                <ul>
                    <li class="footer-item">
                        <a href="" class="footer-link">Hesabım</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Siparişlerim</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Favorilerim</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Takip Ettiklerim</a>
                    </li>

                </ul>
            </div>
            <div class="footer-help">
                <h2 class="footer-title">Yardım</h2>
                <ul>
                    <li class="footer-item">
                        <a href="" class="footer-link">Sıkça Sorulan Sorular</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Nasıl İade Edebilirim </a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">Canlı Yardım</a>
                    </li>
                    <li class="footer-item">
                        <a href="" class="footer-link">İşlem Rehberi</a>
                    </li>
                </ul>
            </div>
            <div>
                <div class="footer-social">
                    <h2 class="footer-title">Sosyal Medya</h2>
                    <ul class="flex gap-x-4">
                        <li>
                            <a href="" class="w-10">
                                <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 448 512">
                                    <path
                                            d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512">
                                    <path
                                            d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"/>
                                </svg>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <svg xmlns="http://www.w3.org/2000/svg" height="1.5em" viewBox="0 0 512 512">
                                    <path
                                            d="M389.2 48h70.6L305.6 224.2 487 464H345L233.7 318.6 106.5 464H35.8L200.7 275.5 26.8 48H172.4L272.9 180.9 389.2 48zM364.4 421.8h39.1L151.1 88h-42L364.4 421.8z"/>
                                </svg>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="footer-payment">
                    <h2 class="footer-title">Güvenli Alışveriş</h2>
                    <div class="footer-payment__logo">
                        <div class="footer-payment__logo__troy"></div>
                        <div class="footer-payment__logo__visa"></div>
                        <div class="footer-payment__logo__master"></div>
                    </div>
                </div>
            </div>

        </div>
    </footer>

    <!-- Bottom Bar-->
    <div class="bottom-bar">
        <div class="container">
            <div class="bottom-bar__copyright">
                <p class="text-white">Copyright 2024 | Powered by DvTech</p>
            </div>
            <div class="bottom-bar__navbar">
                <ul class="bottom-bar__navbar-nav">
                    <li class="bottom-bar__navbar-item">
                        <a href="" class="bottom-bar__navbar-link">Çerez Tercihleri</a>
                    </li>
                    <li class="bottom-bar__navbar-item">
                        <a href="" class="bottom-bar__navbar-link">KVK ve Gizlilik Politikası</a>
                    </li>
                    <li class="bottom-bar__navbar-item">
                        <a href="" class="bottom-bar__navbar-link">Kullanım Koşulları</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
</body>

</html>

templates/shop/index.html
{% extends "base/base.html" %}
{% block title %} Marjikon {% endblock  %}

{% block wrapper %}
    
{% endblock  %}